on: push
permissions:
  contents: write
jobs:
  create-react-app:
    runs-on: ubuntu-latest
    steps:
      - name: 读取仓库
        uses: actions/checkout@v4
      - name: 安装依赖
        run: |
          npm install
          npm run build
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
