on: push
permissions:
  contents: write
jobs:
  # create-react-app:
  dockerbuild:
    runs-on: ubuntu-latest
    steps:
      - name: 读取仓库
        uses: actions/checkout@v4
      # - name: 安装依赖
      #   run: |
      #     npm install
      #     npm run build
      # - name: deploy
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     branch: gh-pages
      #     folder: build
      - name: 登录dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 构建并推送
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: sunxmaz/react-app:latest
